const currencyCountries = [
  { label: "United Arab Emirates Dirham", id: "AED" },
  { label: "Afghan Afghani", id: "ÅFN" },
  { label: "Albanian Lek", id: "ALL" },
  { label: "Armenian Dram", id: "AMD" },
  { label: "Netherlands Antillean Guilder", id: "ANG" },
  { label: "Angolan Kwanza", id: "AOA" },
  { label: "Argentine Peso", id: "ARS" },
  { label: "Australian Dollar", id: "AUD" },
  { label: "Aruban Florin", id: "AWG" },
  { label: "Azerbaijani Manat", id: "AZN" },
  { label: "Bosnia & Herzegovina Convertible Mark", id: "BAM" },
  { label: "Barbadian Dollar", id: "BBD" },
  { label: "Bangladeshi Taka", id: "BDT" },
  { label: "Bulgarian Lev", id: "BGN" },
  { label: "Bahraini Dinar", id: "BHD" },
  { label: "Burundian Franc", id: "BIF" },
  { label: "Bermudian Dollar", id: "BMD" },
  { label: "Brunei Dollar", id: "BND" },
  { label: "Bolivian Boliviano", id: "BOB" },
  { label: "Brazilian Real", id: "BRL" },
  { label: "Bahamian Dollar", id: "BSD" },
  { label: "Bhutanese Ngultrum", id: "BTN" },
  { label: "Botswana Pula", id: "BWP" },
  { label: "Belarus Ruble", id: "BYN" },
  { label: "Belize Dollar", id: "BZD" },
  { label: "Canadian Dollar", id: "CAD" },
  { label: "Congolese Franc", id: "CDF" },
  { label: "Swiss Franc", id: "CHF" },
  { label: "Chilean Peso", id: "CLP" },
  { label: "Chinese Yuan", id: "CNY" },
  { label: "Colombian Peso", id: "COP" },
  { label: "Costa Rican Colon", id: "CRC" },
  { label: "Cuban Convertible Peso", id: "CUC" },
  { label: "Cape Verdean Escudo", id: "CVE" },
  { label: "Czech Republic Koruna", id: "CZK" },
  { label: "Djiboutian Franc", id: "DJF" },
  { label: "Danish Krone", id: "DKK" },
  { label: "Dominican Peso", id: "DOP" },
  { label: "Algerian Dinar", id: "DZD" },
  { label: "Egyptian Pound", id: "EGP" },
  { label: "Eritrean Nakfa", id: "ERN" },
  { label: "Ethiopian Birr", id: "ETB" },
  { label: "Euro", id: "EUR" },
  { label: "Fiji Dollar", id: "FJD" },
  { label: "British Pound Sterling", id: "GBP" },
  { label: "Georgian Lari", id: "GEL" },
  { label: "Ghanaian Cedi", id: "GHS" },
  { label: "Gibraltar Pound", id: "GIP" },
  { label: "Gambian Dalasi", id: "GMD" },
  { label: "Guinea Franc", id: "GNF" },
  { label: "Guatemalan Quetzal", id: "GTQ" },
  { label: "Guyanaese Dollar", id: "GYD" },
  { label: "Hong Kong Dollar", id: "HKD" },
  { label: "Honduran Lempira", id: "HNL" },
  { label: "Croatian Kuna", id: "HRK" },
  { label: "Haiti Gourde", id: "HTG" },
  { label: "Hungarian Forint", id: "HUF" },
  { label: "Indonesian Rupiah", id: "IDR" },
  { label: "Israeli Shekel", id: "ILS" },
  { label: "Indian Rupee", id: "INR" },
  { label: "Iraqi Dinar", id: "IQD" },
  { label: "Indian Rupee", id: "INR" },
  { label: "Iranian Rial", id: "IRR" },
  { label: "Icelandic Krona", id: "ISK" },
  { label: "Jamaican Dollar", id: "JMD" },
  { label: "Jordanian Dinar", id: "JOD" },
  { label: "Japanese Yen", id: "JPY" },
  { label: "Kenyan Shilling", id: "KES" },
  { label: "Kyrgystani Som", id: "KGS" },
  { label: "Cambodian Riel", id: "KHR" },
  { label: "Comorian Franc", id: "KMF" },
  { label: "North Korean Won", id: "KPW" },
  { label: "South Korean Won", id: "KRW" },
  { label: "Kuwaiti Dinar", id: "KWD" },
  { label: "Cayman Islands Dollar", id: "KYD" },
  { label: "Kazakhstan Tenge", id: "KZT" },
  { label: "Laotian Kip", id: "LAK" },
  { label: "Lebanese Pound", id: "LBP" },
  { label: "Sri Lankan Rupee", id: "LKR" },
  { label: "Liberian Dollar", id: "LRD" },
  { label: "Lesotho Loti", id: "LSL" },
  { label: "Libyan Dinar", id: "LYD" },
  { label: "Moroccan Dirham", id: "MAD" },
  { label: "Moldovan Leu", id: "MDL" },
  { label: "Malagasy Ariary", id: "MGA" },
  { label: "Macedonian Denar", id: "MKD" },
  { label: "Myanma Kyat", id: "MMK" },
  { label: "Mongolian Tugrik", id: "MNT" },
  { label: "Macau Pataca", id: "MOP" },
  { label: "Mauritanian Ouguiya", id: "MRO" },
  { label: "Mauritian Rupee", id: "MUR" },
  { label: "Maldivian Rufiyaa", id: "MVR" },
  { label: "Malawi Kwacha", id: "MWK" },
  { label: "Mexican Peso", id: "MXN" },
  { label: "Malaysian Ringgit", id: "MYR" },
  { label: "Mozambican Metical", id: "MZN" },
  { label: "Namibian Dollar", id: "NAD" },
  { label: "Nigerian Naira", id: "NGN" },
  { label: "Nicaragua Cordoba", id: "NIO" },
  { label: "Norwegian Krone", id: "NOK" },
  { label: "Nepalese Rupee", id: "NPR" },
  { label: "New Zealand Dollar", id: "NZD" },
  { label: "Omani Rial", id: "OMR" },
  { label: "Panamanian Balboa", id: "PAB" },
  { label: "Peruvian Nuevo Sol", id: "PEN" },
  { label: "Papua New Guinean Kina", id: "PGK" },
  { label: "Philippine Peso", id: "PHP" },
  { label: "Pakistani Rupee", id: "PKR" },
  { label: "Polish Zloty", id: "PLN" },
  { label: "Paraguayan Guarani", id: "PYG" },
  { label: "Qatari Riyal", id: "QAR" },
  { label: "Romanian Leu", id: "RON" },
  { label: "Serbian Dinar", id: "RSD" },
  { label: "Russian Ruble", id: "RUB" },
  { label: "Rwanda Franc", id: "RWF" },
  { label: "Saudi Riyal", id: "SAR" },
  { label: "Solomon Islands Dollar", id: "SBD" },
  { label: "Seychellois Rupee", id: "SCR" },
  { label: "Sudanese Pound", id: "SDG" },
  { label: "Swedish Krona", id: "SEK" },
  { label: "Singapore Dollar", id: "SGD" },
  { label: "Saint Helena Pound", id: "SHP" },
  { label: "Sierra Leonean Leone", id: "SLL" },
  { label: "Somali Shilling", id: "SOS" },
  { label: "Surinamese Dollar", id: "SRD" },
  { label: "South Sudanese Pound", id: "SSP" },
  { label: "Sao Tome and Principe Dobra", id: "STD" },
  { label: "Syrian Pound", id: "SYP" },
  { label: "Swazi Lilangeni", id: "SZL" },
  { label: "Thai Baht", id: "THB" },
  { label: "Tajikistan Somoni", id: "TJS" },
  { label: "Turkmenistani Manat", id: "TMT" },
  { label: "Tunisian Dinar", id: "TND" },
  { label: "Tonga Paanga", id: "TOP" },
  { label: "Turkish Lira", id: "TRY" },
  { label: "Trinidad and Tobago Dollar", id: "TTD" },
  { label: "New Taiwan Dollar", id: "TWD" },
  { label: "Tanzanian Shilling", id: "TZS" },
  { label: "Ukrainian Hryvnia", id: "UAH" },
  { label: "Ugandan Shilling", id: "UGX" },
  { label: "United States Dollar", id: "USD" },
  { label: "Uruguayan Peso", id: "UYU" },
  { label: "Uzbekistan Som", id: "UZS" },
  { label: "Venezuelan Bolivar", id: "VEF" },
  { label: "Vietnamese Dong", id: "VEF" },
  { label: "Vanuatu Vatu", id: "VUV" },
  { label: "Samoan Tala", id: "WST" },
  { label: "Central African CFA franc", id: "XAF" },
  { label: "East Caribbean Dollar", id: "XCD" },
  { label: "West African CFA franc", id: "XOF" },
  { label: "CFP Franc", id: "XPF" },
  { label: "Yemeni Rial", id: "YER" },
  { label: "South African Rand", id: "ZAR" },
  { label: "Zambian Kwacha", id: "ZMW" },
];

export default currencyCountries;
